AugurProject/augur-node

src/blockchain/log-processors/designated-report-submitted.ts, src/blockchain/log-processors/market-finalized.ts, src/blockchain/log-processors/order-filled.ts, src/blockchain/log-processors/proceeds-claimed.ts, src/blockchain/log-processors/report-submitted.ts, src/blockchain/log-processors/reports-disputed.ts, src/blockchain/log-processors/universe-forked.ts, src/blockchain/log-processors/winning-tokens-redeemed.ts
Really simple PR, but without `callback(null)`, calling an unimplemented log processor causes Knex to hang up/error:
```
Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
debuggability.js:868
at Timeout._onTimeout (/Users/epheph/augur/augur-node/node_modules/knex/lib/client.js:287:18)
at ontimeout (timers.js:471:11)
at tryOnTimeout (timers.js:306:5)
at Timer.listOnTimeout (timers.js:266:5)
```
We haven't run into this yet, because there wasn't an integration of the test emitting contract.
=> Required callback, or knex times out waiting

src/server/getters/get-markets-info.ts, src/types.ts, test/server/getters/get-markets-info.js
https://app.clubhouse.io/augur/story/4254/getmarketsinfo-should-return-a-sorted-array-instead-of-an-object
=> change to sorted array for get-markets-info

src/server/getters/database.ts, src/server/getters/get-account-transfer-history.ts, src/server/getters/get-categories.ts, src/server/getters/get-disputable-markets.ts, src/server/getters/get-market-info.ts, src/server/getters/get-market-price-history.ts, src/server/getters/get-markets-awaiting-designated-reporting.ts, src/server/getters/get-markets-awaiting-reporting.ts, src/server/getters/get-markets-closing-in-date-range.ts, src/server/getters/get-markets-created-by-user.ts, src/server/getters/get-markets-in-category.ts, src/server/getters/get-markets-info.ts, src/server/getters/get-open-orders.ts, src/server/getters/get-reporting-history.ts, src/server/getters/get-reporting-summary.ts, src/server/getters/get-user-trading-history.ts, src/server/getters/get-user-trading-positions.ts
This is a small change now, but I imagine one of the sorting options we're going to want to have is `creationTime`? (even though technically, `creationBlockNumber` will give same sort order)? And that would mean that join would have to happen in all getters, not just those that return full details. I imagine we'll join more tables and want to start following a similar pattern to prevent the join logic from spreading to every getter.
=> centralize join logic for markets

src/server/dispatch-json-rpc-request.ts, src/server/getters/get-markets-created-by-user.ts, src/server/getters/get-markets-info.ts, src/server/getters/get-reporting-history.ts, test/server/getters/get-markets-created-by-user.js, test/server/getters/get-reporting-history.js
suggestions from @adrake33 he found while writing some docs.
Required parameters should come first
getMarketsInfo MUST have marketIDs specified (was optional from when it also took a universe)
actually filter by universe in `markets-created-by-user`
=> small fixes to getter signatures and behavior

src/server/getters/get-reporting-history.ts, src/server/run-websocket-server.ts
Aside from being correct, should help a lot for debugging
/cc @stephensprinkle
=> actually send the error to the websocket client, instead of just logging it

scripts/payloads/getReportingSummary.json, src/server/getters/get-reporting-summary.ts, test/server/getters/get-reporting-summary.js
@stephensprinkle I wasn't 100% sure what results you wanted here, let me know if i should change it. This is basically just a
`count(*) where reportingWindow = ? group by reportingState`
```
$ node test-client.js payloads/getReportingSummary.json
payloads/getReportingSummary.json
{
"id": 11,
"method": "getReportingSummary",
"params": {
"reportingWindow": "0x1000000000000000000000000000000000000000"
}
}
{
"id": 11,
"result": {
"DESIGNATED_REPORTING": 3,
"FIRST_REPORTING": 1
},
"error": null
}
```
=> initial commit of getReportingSummary

src/server/getters/get-open-orders.ts
So we really need to resolve the issue of typescript types being way too loose and not actually ensuring that something that is.
`Address|null`
is not actually `undefined`
This is the third time it has burned us.
=> simple fix for open orders param filtering

scripts/payloads/getOrders-earliestCreationTime.json, src/server/dispatch-json-rpc-request.ts, src/server/getters/get-orders.ts, src/server/getters/get-stake-tokens.ts, test/server/getters/get-orders.js
@bthaile here's what we discussed, applied to getOrders
Without time filter:
```
$ node ../test-client.js getOrders-open.json
getOrders-open.json
{
"id": 3,
"method": "getOpenOrders",
"params": {
"marketID": "0x0000000000000000000000000000000000000001",
"outcome": null,
"orderType": "buy",
"creator": null,
"orderState": "OPEN"
}
}
{
"id": 3,
"result": {
"0x0000000000000000000000000000000000000001": {
"0": {
"buy": {
"0x1000000000000000000000000000000000000000000000000000000000000000": {
"creationBlockNumber": 1400001,
"transactionHash": "0x0000000000000000000000000000000000000000000000000000000000000A00",
"transactionIndex": 0,
"shareToken": "0x1000000000000000000000000000000000000000",
"owner": "0x0000000000000000000000000000000000000b0b",
"creationTime": 1506473500, …
```
=> add earliest and latest CreationTime filter to get-orders, add test

src/blockchain/download-augur-logs.ts
@adrake33 this was causing the issue.
LegacyRepToken.Mint is not defined, and we fall into the parseLog anyway and look for a '.add' member of undefined
/cc @pgebheim since you were on the call, too, when i was mentioning '.add' exceptions
=> Prevents errors in the processLog

src/server/getters/get-account-transfer-history.ts, test/server/getters/get-account-transfer-history.js
```
$ node test-client.js payloads/getAccountTransferHistory-latestCreationTime.json
payloads/getAccountTransferHistory-latestCreationTime.json
{
"id": 2,
"method": "getAccountTransferHistory",
"params": {
"universe": "0x000000000000000000000000000000000000000b",
"account": "0x0000000000000000000000000000000000000b0b",
"token": null,
"latestCreationTime": 1506473475
}
}
{
"id": 2,
"result": [
{
"transactionHash": "0x00000000000000000000000000000000000000000000000000000000deadbeef",
"logIndex": 0,
"creationBlockNumber": 1400000,
"sender": "0x0000000000000000000000000000000000000b0b",
"recipient": "0x000000000000000000000000000000000000d00d",
"token": "0x1000000000000000000000000000000000000000",
"value": 10,
"creationTime": 1506473474,
"blockHash": "0x1400000",
"symbol": …
```
=> add token names, marketID, and outcome to transfer history

src/blockchain/download-augur-logs.ts, src/blockchain/process-block.ts
@tinybike thoughts about correct behavior when processing block fails? there were no existing callbacks in processBlock, so I didn't add it in this PR, but it's probably correct to add it.
I'm doing the whole thing as 1 pass at the beginning to ease de-duplication of blockNumbers without adding extra logic instead of the nested `eachSeries`
=> first pass at downloading blocks when using getAllAugurLogs

Dockerfile, docker-compose.yml
Included is a Docker file which exposes the RPC port (9001) and a docker-compose file which can be used to build and name this image with a :dev tag for convenience.
=> Add Docker support to Augur Node

src/migrations/20171022160433_positions.ts, src/server/getters/get-user-trading-positions.ts, test/blockchain/log-processors/order-filled/index.js, test/server/getters/get-user-trading-positions.js
@stephensprinkle average price is a part of position, but is always 0. I'll implement proper value calculation, but you should be able to move forward since a value will be returned:
```
$ node test-client.js payloads/getUserTradingPositions.json
payloads/getUserTradingPositions.json
{
"id": 6,
"method": "getUserTradingPositions",
"params": {
"universe": "0x6eabb9367012c0a84473e1e6d7a7ce39a54d77bb",
"account": "0x01114f4bda09ed6c6715cf0baf606b5bce1dc96a"
}
}
{
"id": 6,
"result": [
{
"marketID": "0xb2a096ab60fe830cb15c364914e9366d19cb7aa1",
"outcome": 0,
"averagePrice": 0,
"numShares": 0.15,
"numSharesAdjustedForUserIntention": 1.840519140054738,
"realizedProfitLoss": 0,
"unrealizedProfitLoss": -0.15177972552185445
},
{
"marketID": …
```
=> simple addition of averagePrice to position

src/index.ts
This bug existed before. When the merged object was created, it was NOT the one used to connect.
=> fixing bug related to endpoints

package.json
Referenced GitHub issue: https://github.com/mapbox/node-sqlite3/issues/918
Confirmed this as working in both Mac + Linux environments against node latests + lts.
=> bump sqlite3 version to one with available binary for node latest (9.3.0)

src/blockchain/sync-augur-node-with-blockchain.ts, src/index.ts, tsconfig.json
We will need to update the hosted nodes to pass in configs in the new
standard way:
ETHEREUM_HTTP
ETHEREUM_WS
instead of
ENDPOINT_HTTP
ENDPOINT_WS
=> Use named network configs from augur-core

src/server/dispatch-json-rpc-request.ts, src/server/getters/get-markets.ts, src/server/run-server.ts, test/server/getters/get-markets.js
This will allow the UI to filter all market requests by creator for the bug bounty. May provide useful to have one big generic method for other reasons too.
=> just updating get-markets for now. Some other methods could be deprecated for the most part

scripts/payloads/getMarkets-finalized.json, src/blockchain/log-processors/order-filled/update-orders-and-positions.ts, src/blockchain/make-log-listener.ts, src/server/getters/get-dispute-tokens.ts, src/server/getters/get-markets.ts, test/server/getters/get-markets.js
@stephensprinkle I wanted to see if you thought this was acceptable
```
{ "id": 913,
"method": "getMarkets",
"params": 
{ "universe": "0xf7a6dff0f7777cdbf2d1c3b99e0ed08f09d49818",
"reportingState": "FINALIZED",
"sortBy": "reportingStateUpdatedOn",
"isSortDescending": true } }
{
"id": 913,
"result": [
"0x17503d4d710a194aba90d12fec0d353ea7c3ad46",
"0xd60285796b8866e1d9f1fa184b6b77a873ff75dd",
"0xd0558a83e061d8762187725d2b527d42705b3b99",
"0x424b423fb83cbde3c96610bdaf4585c38874765e",
"0x5d68e66b61b90d021ada750c293bb3d983564eea",
"0xa26645b72f7cef94a0989aa4f912557f8d983677",
"0xbff502ecddaf21c75a19ff848ca66d9879d5dfa9",
"0x6ad025e6d606cc52e598b278b5c18a001de2c77a",
"0x9e04f32e06213bd95b35f43bd560ee87b0d8a11b",
"0x65f40d6836f87fcb647dc25adf063c985222f688", …
```
=> join market_state blockNumber to blocks, to allow sorting by a market's last state change

src/blockchain/download-augur-logs.ts, src/blockchain/process-logs.ts, src/server/getters/get-initial-reporters.ts
significantly improve bulk downloading. Before, blocks were downloaded outside of a transaction, and EACH log was processed inside a transaction (not a block's worth)
This makes transactions block-oriented, as well as ensuring the correct
block-logs-block-logs sequential ordering (necessary for advancing time sensibly), and if it stops in the middle, we'll know where to pick up from without duplicating data
=> Fix block/log processing for bulk load 

src/blockchain/log-processors/tokens-transferred.ts
Sometimes this processor receives for Augur.TokensTransferred. Sometimes it receives LegacyRepToken.Transferred. There is slightly different data formats for those, and remove wasn't being flexible
=> we use same log process for native and Augur-based transers. respect logic in remove

src/blockchain/log-processors/crowdsourcer.ts, src/blockchain/log-processors/database.ts, src/server/getters/get-dispute-info.ts
This issue resolves two different issues:
1.) The calculation of which payout had the largest stake was bad, it was sorting on the string literal "sum(amountStaked)" which would randomly select (this would contribute to negative sizes if we didn't flag tentative winning) 
2.) Another crowdsourcer with the same payout would return the wrong object.
=> Fix get dispute

src/blockchain/log-processors/database.ts
Simple mistake, was making tentativeWinning part of the required insert. This is actually sort of an artifact of the contract event ordering issue, because the payout tentativeWinning SHOULD match what is attempting to be inserted, but it doesn't. Either way, this is more correct
=> fix insert payouts

src/server/getters/get-reporting-fees.ts, test/server/getters/get-reporting-fees.js
I'll add a tests and some general cleanup (like parallel, where possible).
```
{ "id": 913,
"method": "getReportingFees",
"params":
{
"universe": "0xcd8569bb29493f01cffc394e050d2533aa5ea824",
"reporter": "0x913da4198e6be1d5f5e4a40d0667f70c0b5430eb"
} }
{
"id": 913,
"result": {
"total": {
"unclaimedEth": "0",
"unclaimedRepStaked": "2098083496093750002",
"unclaimedRepEarned": "1049041748046875001",
"lostRep": "0",
"claimedEth": "4",
"claimedRepStaked": "5",
"claimedRepEarned": "6"
},
"feeWindows": [
"0x6760bfb16e7a402a94269eb60b4eca570bc14df6",
"0x38d9a9951a8dd58c6b2479d1705b62320f0189c2",
"0xf67f60479591f147be131a60253a691bb8e6d854",
"0x2a9d1ed97689f14056c79ab8b33df244019b16c6",
"0x9b9003fb915871c30a3cff62c747b43a8538b682",
"0x0d1b6484a9b11b5b7a28ada2e5ca33cdd84841a2", …
```
=> Add repStaked/Earned to getReportingFees

src/server/dispatch-json-rpc-request.ts, src/server/getters/get-initial-reporters.ts, test/server/getters/get-initial-reporters.js
It was trying to get a REP contract address from the ether and was never working probably. Now it takes a universe and gets the rep contract associated with it.
=> take universe as part of the initial reporters request

src/blockchain/log-processors/crowdsourcer.ts, src/blockchain/log-processors/index.ts, src/blockchain/log-processors/market-created.ts, src/blockchain/log-processors/market-migrated.ts, src/blockchain/log-processors/market-participants-disavowed.ts, src/blockchain/log-processors/universe-forked.ts, src/migrations/20171005123235_markets.ts, src/migrations/20180122152117_crowdsourcers.ts, src/seeds/test/crowdsourcer.ts, src/seeds/test/markets.ts, src/types.ts, test/blockchain/log-processors/crowdsourcers.js, test/blockchain/log-processors/market-created.js, test/blockchain/log-processors/market-migrated.js, test/blockchain/log-processors/market-participants-disavowed.js, test/blockchain/log-processors/universe-forked.js
As discussed in Discord I didn't make `disavowed` an enum and instead kept it as boolean since the one case we needed that implicitly has the state of "needs disavowal" (forked market + not disavowed).
I added `needsDisavowal` for markets in a forking universe that haven't been migrated or disavowed.
Migration and manual disavowal will now mark all the market's crowdsourcers as disavowed as well.
=> add "needsDisavowal" for markets and make "disavowed" account for cases

src/server/getters/get-reporting-fees.ts, test/server/getters/get-reporting-fees.js
The two relevant ones that are actually fixed are:
https://app.clubhouse.io/augur/story/10864/getreportingfees-returns-unclaimedforkfees-after-rep-is-migrated
and
https://app.clubhouse.io/augur/story/10843/unmade-unfilled-dispute-bonds-can-t-be-reclaimed-by-disputer
This also partially addresses
https://app.clubhouse.io/augur/story/10842/unclaimedeth-has-incorrect-balance-for-initial-reporter-when-there-was-no-dispute
but leaves a lot to be done there (see CH comment)
=> fixes for various get reporting fees issues

src/blockchain/log-processors/order-filled/index.ts, test/blockchain/log-processors/order-filled/index.js
Story details: https://app.clubhouse.io/augur/story/10359
After the new version
=> [AFTER augur-core -7] Get user trading history is returning too many share amounts

src/blockchain/log-processors/order-filled/refresh-position-in-market.ts, src/blockchain/log-processors/order-filled/upsert-position-in-market.ts, test/blockchain/log-processors/completesets.js, test/blockchain/log-processors/order-filled/index.js, test/blockchain/log-processors/tokens-transferred.js
Story details: https://app.clubhouse.io/augur/story/11255
In the volumetrics code -- we updated the price from the contracts and converted it from fixed-point to decimal. However, this conversion incorrectly ignored the scaling for scalar markets. The outcome was that the price on the `outcomes` table was incorrect.
=> Weird Scalar Trading Bug

src/blockchain/log-processors/market-created.ts, src/server/getters/get-user-share-balances.ts
I missed the share-token filter and thus when we went through reporting rounds we returned 0 balance for all the crowdsourcers as well.
=> Fix issue with too many share balances being returned

src/blockchain/log-processors/order-canceled.ts
orderType is translated to buy | sell in Order Created, Order Filled, but order canceled gets 0 | 1. This will make it consistent so the UI handler can just handle "buy" and "sell"
=> contract orderType leaks through and UI gets confused

src/blockchain/log-processors/order-canceled.ts, src/migrations/20180504123242_orders_canceled.ts, src/seeds/test/orders_canceled.ts, test/blockchain/log-processors/order-canceled.js
Story details: https://app.clubhouse.io/augur/story/11966
=> Augur-node should save cancelled orders as new transactions instead of updating the original order transaction's status

src/server/getters/get-orders.ts, src/types.ts, test/server/getters/get-orders.js
response object looks like this now:
```
{
"0x0000000000000000000000000000000000000001": {
1: {
sell: {
"0x4200000000000000000000000000000000000000000000000000000000000000": {
orderId: "0x4200000000000000000000000000000000000000000000000000000000000000",
shareToken: "0x2000000000000000000000000000000000000000",
transactionHash: "0x0000000000000000000000000000000000000000000000000000000000000A05",
logIndex: 0,
owner: "0x000000000000000000000000000000000000d00d",
creationTime: 1506473515,
creationBlockNumber: 1400002,
orderState: "CANCELED",
price: "0.8",
amount: "2",
fullPrecisionPrice: "0.8",
fullPrecisionAmount: "2",
tokensEscrowed: "1.2",
sharesEscrowed: "0",
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
canceledBlockNumber: 1500000,
canceledTransactionHash: …
```
=> Add cancelation tx details to orders object, if order state is canceled

src/blockchain/log-processors/order-filled/index.ts, src/blockchain/log-processors/order-filled/update-orders-and-positions.ts, test/unit/blockchain/log-processors/order-filled/index.js
Fetching order amount from the chain is not good when freshly sync'ing a new node. That order could be gone, or could be partially taken and the update happens out of order.
the test data here was inconsistent before (an order ended up with MORE amount after an order was filled), cleaned it up.
=> Remove off-chain call for order amount

src/blockchain/process-block.ts
regardless of how big backing array is
=> Add function to completely wipe state of override timestamp

package-lock.json, package.json, src/controller.ts, src/setup/check-and-initialize-augur-db.ts, src/utils/logger/logger.ts
- Clears the loggers out on shutdown
- Clears and starts the process queue back up again when starting up
- Saves last known upload block for the netID to a file and on change will delete the corresponding DB and update the upload block number. This will remove the need to delete dbs manually on testnets
=> Various fixes

src/events.ts
If a user has multiple local connections, or refreshes before the websocket stuff can timeout, this will emit warnings
=> Suppress EventEmitter warnings, since we don't know how many users will be using subscriptions

src/controller.ts, src/runServer.ts
https://app.clubhouse.io/augur/story/13690/augur-app-design-adjustments
augur-app doesn't know when to restart after `reset database`, adding callbacks.
also added passing in networkId so the reset database method knows what database to rename. If augur controller has never started then `this.augur.rpc.getNetworkID();` always returns null and mainnet database gets reset.
=> add callbacks so augur-app knows when to start back up after reset

src/blockchain/log-processors/crowdsourcer.ts, src/blockchain/log-processors/initial-report-submitted.ts, src/blockchain/log-processors/market-created.ts, src/blockchain/log-processors/market-finalized.ts, src/blockchain/log-processors/order-filled/update-volumetrics.ts, src/blockchain/log-processors/reporting-participant-disavowed.ts, src/blockchain/log-processors/token/burn.ts, src/blockchain/log-processors/token/mint.ts, src/blockchain/process-block.ts, src/server/getters/get-dispute-info.ts, src/server/getters/get-fee-window-current.ts, src/server/getters/get-markets-info.ts, src/server/getters/get-reporting-fees.ts, src/server/getters/get-reporting-history.ts, src/utils/convert-fixed-point-to-decimal.ts, test/unit/blockchain/log-processors/fee-window-created.js, test/unit/blockchain/log-processors/market-created.js, test/unit/blockchain/log-processors/market-finalized.js, test/unit/blockchain/log-processors/order-canceled.js, test/unit/blockchain/log-processors/order-filled/index.js, test/unit/blockchain/log-processors/reporting-participant-disavowed.js, test/unit/blockchain/log-processors/universe-forked.js
Serialize things that are going to be done sequentially anyway, due to sqlite. I'm unsure why we were seeing these race conditions but doing them in parallel is not faster, and has the possibility to be slower.
I kept parallel for things that make off-chain calls, since those benefit from parallelism.
=> Serialize DB access on sqlite.

src/blockchain/monitor-ethereum-node-health.ts
Now that we return an error on a failing eth_call, the message here for universe not existing is not friendly.
=> Inform user of the likely config issue (instead of just eth_call returned 0x)

src/blockchain/download-augur-logs.ts, src/blockchain/process-block.ts
We use promises to download block details and start that process on receipt of a batch of logs, not when those logs are processed (which could be much later and happens inside of a transaction while everything else is stopped).
In this PR we also fix the "double transaction" that occurs during bulk sync
=> Speed up block details download

src/blockchain/log-processors/token/increase-token-supply.ts, src/setup/check-and-initialize-augur-db.ts
@nuevoalex whenever the DB was newly created, we were always comparing `0 != real-block-number`, and then attempting a rename on a file that didn't exist.
=> Fix UnhandledPromiseRejectionWarning in db creation

src/blockchain/log-processors/order-filled/update-volumetrics.ts, src/migrations/20180907121300_outcome_market_share_volume.ts, test/unit/blockchain/log-processors/order-filled/index.js
The previous logic was calculating volume by multiplying display share amount by on chain price. It should be using display price since the intended use case is for displaying the volume in ETH.
For scalar markets the display price have a different starting value for its range. We compensate for this by subtracting the minimum price in the range to get the actual price of 1 share in terms of ETH.
You can see how this change manifests in the tests giving us sensible and understandable values for volume. For example in the first test case a trade occurs for 1 display Share at price .7. The ETH volume here should be .7, not 7000 as it was previously.
=>  volume based in ETH now

src/blockchain/bulk-sync-augur-node-with-blockchain.ts
So for context this was resulting in an error during blockstream which would halt the stream but allow AN to continue running. That seems like a larger issue that should be addressed at some point. The visible results were that AN wasn't updating (obv) and other strange behavior in the UI like no time data being available (the original bug this issue was for).
What was occurring was that in the case the user was up to date but within the handoff block window this code would simply make them fetch just the block they last synced +1. This effectively gets rid of any handoff block window and also allows the sync to start at a block that doesn't yet exist in the case where the user's latest synced block is also the highest block. The later case is what was causing the error  that was …
=> remove case that undermines the actual check being done

src/blockchain/bulk-sync-augur-node-with-blockchain.ts
About that thing you said about how the call to get the block number curiously wasn't async...
Also the bit added about skipping bulk download: It occurred to me if we encounter this case its silly do do bulk download since we are so caught up we're only waiting for the benefit of blockstream. That and the ethrpc code doesn't actually update its known highest block before starting the bulk request which makes this case fail when we wait like this.
=> the block number given by rpc is static. Need to actually make request

src/blockchain/bulk-sync-augur-node-with-blockchain.ts
How's this look?
```
The Ethereum node has not processed enough blocks (5) since last sync
Current Block: 7011618
Last Sync Block: 7011615
Blocks to wait: 2
The Ethereum node has not processed enough blocks (5) since last sync
Current Block: 7011619
Last Sync Block: 7011615
Blocks to wait: 1
Skipping batch load
Bulk sync with blockchain complete.
Starting blockstream at block  7011615
```
=> Fixes augur#359 . Improve text related to blockstream block window

src/setup/check-and-initialize-augur-db.ts
It was possible for the user to "reset database" then try to import warp file. This resulted in error b/c augur db file wouldn't exist. Needed to check before renaming.
=> add check to make sure db file exists before renaming it

knexfile.js, scripts/osx-copy-augur-app-db-to-augur-node-cli, src/runServer.ts
This helper script will _overwrite_ your current augur-node cli database
with the DB from your OSX installed Augur App, and apply latest migrations
to the new cli db.
Why? In my workflow, my OSX installed Augur App is often at HEAD of
blockstream, but I frequently need to reset my augur-node CLI database.
=> Add 'yarn osx-copy-augur-app-db-to-augur-node-cli'

src/controller.ts, src/sync/file-operations.ts
add getters for system db version and user's highest db version based on scanning user's data directory for `augur-1-`. In this case we are only interested in mainnet databases. This give information to augur-app to inform user when they have to resync.
=> add getters for user and system db versions

src/blockchain/log-processors/completesets.ts, src/blockchain/log-processors/order-filled/index.ts, src/blockchain/log-processors/profit-loss/update-profit-loss.ts, src/blockchain/log-processors/trading-proceeds-claimed.ts, src/server/getters/get-profit-loss.ts, src/server/getters/get-user-trading-positions.ts, test/unit/server/getters/get-profit-loss.js, test/unit/server/getters/get-user-trading-positions.js
We want:
- Avg price to always be the price of the long position even when for a short
- Unrealized to produce the correct value using this avg price
- Realized Profit to be recorded relative to the outcome being traded, regardless of long or short
- Scalar profit to properly be calculated when shorting
This set of changes should cover that. Due to these changes we could remove the realized profit summing as well since that will be covered by the new realized profit behavior
=> Fix short price unrealized realized

src/server/getters/get-markets.ts, test/unit/server/getters/get-markets.js
Backwards compatible. Related to AugurProject/augur#812
=> Support filtering by a list of ReportingState in getMarkets() API

knexfile.js, src/blockchain/log-processors/order-filled/update-volumetrics.ts, src/blockchain/rebuild-volume-for-all-markets.ts, src/migrations/20190201161645_rebuild_volume_for_all_markets.ts
rebuildVolumeForAllMarkets() was added to facilitate a recent volume fix which
required a full DB reset.
It can also be used in future unit testing to verify that incremental and
non-incremental methods of volume calculation produce the correct result.
Or as an ongoing sanity check: executing rebuildVolumeForAllMarkets() on a
production database should result in no changes.
Related to AugurProject/augur#289
=> Add rebuildVolumeForAllMarkets() and migration to run it

src/blockchain/process-block.ts
We didn't manually convert from hex to int during reorg, so the code works on sqlite but not postgres.
=> Fixes augur#811

package.json, src/blockchain/log-processors/completesets.ts, src/migrations/20190205102050_rm_complete_sets_trade_group_id.ts, src/types.ts, test/unit/blockchain/log-processors/completesets.js
TradeGroups are a part of the order system, but not a part of CompleteSets directly.
Good thing, too, because integer is not a valid sqlite storage for a bytes32 value. Just get rid of it.
=> Remove tradegroup from completeSets

src/server/getters/get-market-price-candlesticks.ts, test/unit/server/getters/get-market-price-candlesticks.js
`Candlestick.volume` uses new volume business definition via `volumeForTrade()`
to be consistent with markets/outcomes.volume.
Added `Candlestick.shareVolume`, a new name for `Candlestick.tokenVolume`
to be consistent with markets/outcomes.volume. `Candlestick.tokenVolume` should
be removed once UI updated to use `Candlestick.shareVolume`.
`Candlestick.shareVolume/tokenVolume` uses same business definition as
markets/outcomes.shareVolume.
Fixes AugurProject/augur#1002
=> Use new business definitions for Candlestick.volume/shareVolume

src/server/getters/get-user-trading-positions.ts
fixes https://github.com/AugurProject/augur/issues/1113
```
getter error: TypeError: Cannot read property 'abs' of undefined
at _.filter (/Users/bthaile/gitrepos/augur-node.git/src/server/getters/get-user-trading-positions.ts:116:46)
at /Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:2935:13
at /Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:4925:15
at baseForOwn (/Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:3010:24)
at /Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:4894:18
at baseFilter (/Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:2934:7)
at Function.filter (/Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:9173:14)
at …
```
=> need to guard against largestShort being undefined

src/server/dispatch-json-rpc-request.ts, src/server/getters/get-platform-activity-stats.ts, test/unit/server/getters/get-platform-activity-stats.js
Provides
-Active Users
- number of Trades
- Open Interest
- Markets Created
- Volume
- Money at Stake
=> augur-1192 ads platform activity stats to api

package.json, src/blockchain/log-processors/profit-loss/update-profit-loss.ts, src/migrations/20190201155650_wcl_profit_loss_timeseries.ts, src/server/getters/get-profit-loss.ts, src/server/getters/get-user-trading-positions.ts, src/server/post-process-database-results.ts, src/utils/dimension-quantity.ts, src/utils/financial-math.ts, test/unit/server/getters/get-user-trading-positions.js, tsconfig.json, tslint.json, yarn.lock
I'll write a better commit msg for the merge.
We'd like to merge this now so UI team can continue testing. After the merge I'll continue working on this:
1. clean up comments in financial-math and dimension-quantity
2. move financial-math to its own npm module or monorepo subdir ?? (might name it `augur-math`)
3. move dimension-quantity to its own npm module (might name it `ts-quantity`)
=> Add P&L percents and financial math library

src/server/getters/get-account-transaction-history.ts, src/types.ts, yarn.lock
Fixes https://github.com/AugurProject/augur/issues/1515, where outcomes/outcome descriptions were sometimes getting returned as null (for example, yes/no markets or scalar markets).
In cases of market creation, particpation token, or complete set txs, both `outcome` & `outcomeDescription` will still be null. `outcome` can also be set to null if the outcome is invalid (however, `outcomeDescription` will be set to "Invalid").
=> Fix Outcomes/Outcome Descriptions for getAccountTransactionHistory

src/server/getters/get-profit-loss.ts, src/server/getters/get-user-trading-positions.ts, src/utils/financial-math.ts, test/unit/server/getters/get-user-trading-positions.js
Add tradingPositionsTotal to getUserTradingPositions()
This is a backwards-incompatible change to public API getUserTradingPositions()
Fixes AugurProject/augur#1647
1. Adds GetUserTradingPositionsResponse.tradingPositionsTotal, a portfolio-level
aggregation of trading positions.
2. GetUserTradingPositionsResponse.{tradingPositionsTotal,frozenFundsTotal} are
now defined if and only if UserTradingPositionsParams.marketId is undefined.
Ie. the totals are provided if and only if request is _not_ filtered by market.
This is because data to compute totals is (locally) unavailable when filtering
by marketId.
=> Add tradingPositionsTotal to getUserTradingPositions()

src/server/getters/get-account-transaction-history.ts
Fixes https://github.com/AugurProject/augur/issues/1761. For yes/no & categorical markets, the complete set buy/sell price should always be 1 ETH. For scalar markets, it should always be maxPrice -minPrice.
=> Fix complete sets price

src/runServer.ts
Allow user to specify the number of blocks fetched at once, which lets
them set a configuration to a value that makes sense for their system.
For Infura's limit of 1000 logs returned, tune this value to 10.
Default Value: 720 blocks per chunk
=> Fixes #848

src/blockchain/log-processors/profit-loss/update-profit-loss.ts, src/migrations/20190201155650_wcl_profit_loss_timeseries.ts, src/server/getters/get-profit-loss.ts, src/utils/financial-math.ts, test/unit/server/getters/get-user-trading-positions.js
getUserTradingPositions() returns unrealizedRevenue24hAgo and
unrealizedRevenue24hChangePercent, which are dependencies for the UI's "My
"Active Markets" screen, which shows 24 hour percent change in a position's
unrealizedRevenue. The "percent change" is based on a comparison with the last
trade price paid by anybody now vs. 24 hours ago.
This change adds new behavior: if you opened (or further opened) your position
in the last 24 hours, we want the "24 hour ago" comparison price to be the price
you paid to open instead of the actual last price 24 hours ago. This prevents
someone from opening a position and then immediately seeing a "gain" or "loss"
based on the (irrelevant) last trade price from 24 hours ago.
Requires a DB rebuild due to backwards-incompatible change to …
=> Use "your" price to calc unrealizedRevenue24hAgo if you traded in last 24h

src/blockchain/log-processors/market-finalized.ts, src/blockchain/log-processors/order-filled/index.ts, src/blockchain/log-processors/profit-loss/update-outcome-value.ts, src/migrations/20190422154621_add_blockNumber_logIndex_to_outcome_value_timeseries.ts, src/server/getters/get-profit-loss.ts
The DB table outcome_value_timeseries uses timestamp as the sort column, but
trades in the same block may have the same timestamp, preventing clients of
outcome_value_timeseries from determining the correct trade order.
Also sort by (timestamp, blockNumber, logIndex) instead of just timestamp in
queryOutcomeValueTimeseries, the only client of outcome_value_timeseries.
Fixes AugurProject/augur#1634
=> Add blockNumber, logIndex to DB table outcome_value_timeseries

src/blockchain/log-processors/profit-loss/update-profit-loss.ts
During self trades, there are two PL rows generated for one logIndex.
Since we weren't taking this into accoutn in the query, the natural
ordering of SQLite meant the `limit 1` was picking up the first half
of the trade via the first PL row.
Added ordering by rowid DESC in order to make sure the LAST trade
generates the PL we are using to determine how the positions change over
time.
=> Fixes #1849

src/blockchain/log-processors/order-canceled.ts, src/blockchain/log-processors/order-created.ts, src/blockchain/log-processors/order-filled/index.ts, src/blockchain/log-processors/profit-loss/frozen-funds.ts, src/blockchain/log-processors/profit-loss/update-profit-loss.ts, src/migrations/20190201155650_wcl_profit_loss_timeseries.ts, src/seeds/test/wcl_profit_loss_timeseries.ts, src/server/getters/get-profit-loss.ts, src/server/post-process-database-results.ts, test/unit/blockchain/log-processors/order-canceled.js, test/unit/blockchain/log-processors/order-created.js, test/unit/blockchain/log-processors/profit-loss/frozen-funds.ts
Frozen funds now includes tokens escrowed for open orders.
Frozen funds now handles self-filled trades: if a trade is self-filled (ie. user
traded with themselves), then the OrderCreated log looks the same as if the
trade was not self-filled, but the contracts silently skip creating complete
sets, instead returning tokens to the user. So augur-node deducts these tokens
from frozen funds to handle this on-chain exception.
AugurProject/augur#1869 AugurProject/augur#1852
=> Handle open orders and self-trades in frozen funds

src/migrations/20190205102050_rm_complete_sets_trade_group_id.ts, test/unit/blockchain/log-processors/completesets.js
This migration dropped column completeSets.tradeGroupId
This migration always fails since commit cd2ceba73 which added
`numCompleteSets: true` to post-process-database-results. It always fails
because sqlite doesn't support drop column natively and Knex implements this
internally by using a temp table; that temp table is affected by
post-process-database-results because the completeSets.numCompleteSets column
is converted to BigNumber when Knex reads it and then that BigNumber fails to
be written into the temp table.
The fix is to make the migration a no-op without actually deleting it.
This allows clients who already ran the migration to still find the migration
file (and Knex checks for this), but clients who haven't yet run the migration
will succeed because it's a no-op.
=> Disable 20190205102050_rm_complete_sets_trade_group_id.ts

src/migrations/20190620173723_rebuild_liquidity_metrics.ts, src/server/getters/get-categories.ts, src/server/getters/get-markets.ts, src/types.ts, src/utils/dimension-quantity.ts, src/utils/liquidity.ts, test/unit/server/getters/get-categories.js
This PR completes some line items from https://github.com/AugurProject/augur/issues/2328:
1. Only show tags and categories based on what markets pass the filter. Rank tags and categories by liquidityTokens of markets within them.
2. Use 100% spread for "Liquidity - All Spreads".
3. In liquidityTokens algorithm sell a smaller increment of 0.02 ETH so that markets with less liquidity survive spread filter.
=> Liquidity filter cleanup

src/utils/gas.ts
reduce freq we are calling eth gas station to get gas prices. Instead of every minute change to every hour.
=> rate limit calls to ethgasstation to once per hour

src/migrations/20190524103839_add_outcomes_liquidity_and_markets_liquidity.ts
Added quotes and a subquery alias. Without quotes, the camel case names won't stick and the query will error if you don't add an alias for a subquery.
=> Update markets_liquidity CREATE VIEW for Postgres
