AugurProject/augur-node

- .travis.yml
- tsconfig.json
Seeing if this works on Travis.
> First cut, fix travis

- src/blockchain/start-augur-listeners.ts
- src/blockchain/sync-augur-node-with-blockchain.ts
Wait for the initial block to load from the blockchain and use this
block number to calculate the range to bulk fetch.
> Sync all missing rows in initial sync

- src/index.ts
> Suppress warning for Sqlite3 DEFAULT usage

- .travis.yml
- package-lock.json
- package.json
- src/constants.ts
- src/server/getters/get-account-transfer-history.ts
- src/server/getters/get-categories.ts
- src/server/getters/get-markets-info.ts
- tsconfig.json
Generate declaration files to start packaging this as a module
> Generate declaration files

- src/blockchain/log-processors/designated-report-submitted.ts
- src/migrations/20171005123235_markets.ts
- src/migrations/20171011152617_reports.ts
- src/migrations/20171015155157_reports_designated.ts
- src/migrations/20171017150457_market_state.ts
Need to write tests, but I wanted a review of my work first, since it's my first log-processor commit, as well as the first primary/autoincrement table.
> designated-report-submitted log processor

- src/server/getters/get-markets-awaiting-designated-reporting.ts
- src/server/getters/get-markets-info.ts
- test/server/getters/get-markets-awaiting-designated-reporting.js
> First pass at get-markets-awaiting-designated-reporting

- src/server/getters/get-account-transfer-history.ts
- src/server/getters/get-all-reporting-tokens.ts
- src/server/getters/get-categories.ts
- src/server/getters/get-closed-orders.ts
- src/server/getters/get-detailed-market-info.ts
- src/server/getters/get-disputable-markets.ts
- src/server/getters/get-market-info.ts
- src/server/getters/get-market-price-history.ts
- src/server/getters/get-markets-awaiting-all-reporting.ts
- src/server/getters/get-markets-awaiting-designated-reporting.ts
- src/server/getters/get-markets-awaiting-limited-reporting.ts
- src/server/getters/get-markets-closing-in-date-range.ts
- src/server/getters/get-markets-created-by-user.ts
- src/server/getters/get-markets-in-category.ts
- src/server/getters/get-markets-info.ts
- src/server/getters/get-open-orders.ts
- src/server/getters/get-reporting-history.ts
- src/server/getters/get-reporting-summary.ts
- src/server/getters/get-reporting-windows-with-unclaimed-fees.ts
- src/server/getters/get-unclaimed-reporting-tokens.ts
- src/server/getters/get-unfinalized-reporting-tokens.ts
- src/server/getters/get-user-trading-history.ts
- src/server/getters/get-user-trading-positions.ts
re: @MicahZoltu 's comment in #23
> no undefined for Err across all getters

- src/server/getters/get-categories.ts
- src/server/getters/get-market-info.ts
- src/server/getters/get-markets-closing-in-date-range.ts
- src/server/getters/get-markets-created-by-user.ts
- src/server/getters/get-markets-in-category.ts
- test/server/getters/get-categories.js
- test/server/getters/get-markets-closing-in-date-range.js
- test/server/getters/get-markets-created-by-user.js
- test/server/getters/get-markets-in-category.js
Small change, but it's how I implemented #32 , so I wanted to make it consistent.
> be consistent about empty array vs. undefined in response

- scripts/test-client.js
- src/blockchain/download-augur-logs.ts
- src/blockchain/log-processors/designated-report-submitted.ts
- src/blockchain/log-processors/index.ts
- src/blockchain/log-processors/legacy-rep-contract/approval.ts
- src/blockchain/log-processors/legacy-rep-contract/transfer.ts
- src/blockchain/log-processors/market-created.ts
- src/blockchain/log-processors/market-finalized.ts
- src/blockchain/log-processors/order-canceled.ts
- src/blockchain/log-processors/order-created.ts
- src/blockchain/log-processors/order-filled.ts
- src/blockchain/log-processors/proceeds-claimed.ts
- src/blockchain/log-processors/report-submitted.ts
- src/blockchain/log-processors/reports-disputed.ts
- src/blockchain/log-processors/tokens-transferred.ts
- src/blockchain/log-processors/universe-forked.ts
- src/blockchain/log-processors/winning-tokens-redeemed.ts
- src/blockchain/make-log-listener.ts
- src/blockchain/process-logs.ts
- src/migrations/20171005123242_orders.ts
- src/migrations/20171005131812_tokens.ts
- src/seeds/test/tokens.ts
- src/server/getters/get-open-orders.ts
- src/types.ts
- test/blockchain/log-processors/market-created.js
Added log removal support for Approval, Transfer, MarketCreated, OrderCanceled, OrderCreated, and OrderFilled events.  @epheph let me know you think if this looks like a reasonable approach to log removal!
> Adds log removal support

- src/migrations/20171027152617_network_id.ts
> match type returned from rpc and used for comparison

- package.json
- scripts/replace-user.js
added simple script so UI team can change mock user to their geth user and test UI.
> add script to change the mock user hash so UI can test.

- src/server/getters/get-markets-info.ts
- test/server/getters/get-markets-info.js
> Allow empty MarketIDs array

- src/server/getters/get-user-trading-positions.ts
> return better error on missing required parameter

- src/server/getters/get-market-price-history.ts
- src/server/getters/get-open-orders.ts
- src/server/getters/get-reporting-history.ts
- src/server/getters/get-user-trading-history.ts
- test/server/getters/get-market-price-history.js
- test/server/getters/get-open-orders.js
- test/server/getters/get-reporting-history.js
- test/server/getters/get-user-trading-history.js
> making object getter return {} instead of null

- src/server/getters/get-open-orders.ts
Need to join markets so that filtering by universe works
> join market to filter on universe

- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-markets-awaiting-designated-reporting.ts
- src/server/getters/get-markets-awaiting-reporting.ts
- src/server/getters/get-markets-closing-in-date-range.ts
- src/server/getters/get-markets-created-by-user.ts
- src/server/getters/get-markets-in-category.ts
- src/server/getters/get-markets.ts
> quick fixes

- src/server/getters/get-disputable-markets.ts
- src/server/getters/get-reporting-windows-with-unclaimed-fees.ts
> Add placeholder

- src/migrations/20171011152617_reports.ts
- src/seeds/test/reports.ts
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-reporting-history.ts
- src/types.ts
- test/server/getters/get-reporting-history.js
> timestamp and transactionHash/index support for reporting-history

- src/blockchain/download-augur-logs.ts
> If we bail on that log processor, make sure we hand back iteration for the next event in series

- src/blockchain/process-block.ts
- src/blockchain/start-augur-listeners.ts
- src/blockchain/sync-augur-node-with-blockchain.ts
- src/types.ts
> Change process-block to accept actual block object, not just number

- scripts/payloads/getAccountTransferHistory-latestCreationTime.json
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-account-transfer-history.ts
- test/server/getters/get-account-transfer-history.js
```
$ node ../test-client.js getAccountTransferHistory-latestCreationTime.json
getAccountTransferHistory-latestCreationTime.json
{
"id": 2,
"method": "getAccountTransferHistory",
"params": {
"universe": "0x000000000000000000000000000000000000000b",
"account": "0x0000000000000000000000000000000000000b0b",
"token": null,
"latestCreationTime": 1506473475
}
}
{
"id": 2,
"result": [
{
"transactionHash": "0x00000000000000000000000000000000000000000000000000000000deadbeef",
"logIndex": 0,
"creationBlockNumber": 1400000,
"sender": "0x0000000000000000000000000000000000000b0b",
"recipient": "0x000000000000000000000000000000000000d00d",
"token": "0x1000000000000000000000000000000000000000",
"value": 10,
"creationTime": 1506473474,
"blockHash": "0x1400000"
}
],
"jsonrpc": "2.0"
} …
```
> account transfer timestamps & filtering

- src/blockchain/log-processors/order-created.ts
> Hack to fix missing fields for now

- scripts/payloads/getBetterWorseOrders.json
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-better-worse-orders.ts
Just the initial version to unblock @JohnDanz
> getBetterWorseOrders

- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-better-worse-orders.ts
- test/server/getters/get-better-worse-orders.js
> change normalizedPrice to price

- package-lock.json
- src/migrations/20171005123325_approvals.ts
- src/migrations/20171005123329_transfers.ts
> Update constraint names

- package-lock.json
- src/blockchain/log-processors/order-filled/calculate-fill-price.ts
- src/blockchain/log-processors/order-filled/index.ts
- src/blockchain/log-processors/order-filled/update-volumetrics.ts
- test/blockchain/log-processors/order-filled/index.js
Convert to human-readable share quantities for the UI (and for augur-node's internal use).  Note: the matching changes in augur.js are in https://github.com/AugurProject/augur.js/pull/191
> 4911 human readable shares

- src/blockchain/log-processors/market-created.ts
- src/types.ts
- test/blockchain/log-processors/market-created.js
> ensure extraInfo is at least an object

- src/server/getters/get-better-worse-orders.ts
> correct error msg

- src/blockchain/log-processors/designated-report-submitted.ts
- src/blockchain/log-processors/market-finalized.ts
- src/blockchain/log-processors/order-canceled.ts
- src/blockchain/log-processors/report-submitted.ts
- src/blockchain/log-processors/reports-disputed.ts
- src/blockchain/log-processors/token/approval.ts
- src/blockchain/log-processors/token/burn.ts
- src/blockchain/log-processors/tokens-transferred.ts
- src/blockchain/log-processors/trading-proceeds-claimed.ts
- src/blockchain/log-processors/universe-forked.ts
- src/blockchain/log-processors/winning-tokens-redeemed.ts
@stephensprinkle 
https://app.clubhouse.io/augur/story/5019/tokenstransferred-event-not-emitted-when-transfering-tokens
> add emitters for a bunch of stuff, while i was doing TokensTransferred

- .gitignore
- Dockerfile
- docker-entrypoint.sh
@MicahZoltu per our docker cloud discussion
> simple change to copy augur.db during entrypoint, not during build

- config.json
> default to localhost instead of rinkeby

- src/index.ts
@MicahZoltu per our discussion
> use env OR defaults, not both

- src/blockchain/sync-augur-node-with-blockchain.ts
> use a default blockNumber of 0 if we have no record of that networkID

- package-lock.json
- package.json
- src/blockchain/log-processors/market-created.ts
- test/blockchain/log-processors/market-created.js
Trivial update.... the real work is yet to come @epheph @pgebheim  :fearful:
> New new reporting

- src/blockchain/process-block.ts
> in case of a lookup error, do not also cause a tx leak error

- src/server/address-format-reviver.ts
- src/server/run-websocket-server.ts
- test/server/address-format-reviver.js
https://app.clubhouse.io/augur/story/5104/deal-with-variably-padded-addresses
> Deal with variably padded addresses

- src/blockchain/log-processors/market-created.ts
- test/blockchain/log-processors/market-created.js
> fix reference to outcomes

- src/server/run-server.ts
@pgebheim  I based this on your branch to avoid merge conflicts.
> /status/blockage

- scripts/payloads/getContractAddresses.json
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-contract-addresses.ts
- src/server/run-server.ts
- src/server/run-websocket-server.ts
- test/server/getters/get-contract-addresses.js
Tests are broken, but i wanted to discuss the approach before fixing them
> getter for getContractAddresses

- src/blockchain/sync-augur-node-with-blockchain.ts
- src/index.ts
Requires https://github.com/AugurProject/augur.js/pull/207
> Exit on ethereum node disconnect

- src/blockchain/download-augur-logs.ts
- src/blockchain/process-block.ts
- src/blockchain/process-queue.ts
- src/blockchain/start-augur-listeners.ts
this PR just puts callbacks in place for the next PR
> callbacks for processing blocks, to support linearizing

- src/blockchain/process-block.ts
- src/blockchain/sync-augur-node-with-blockchain.ts
> Wrong comparison in advanceTime

- knexfile.js
Important for seed data based on how i structured payouts seed
> match actual usage, makes seed data easier to write

- src/blockchain/process-block.ts
Now that we expose fee windows, it depends on logic to advance the time forward (since blocktime exceeding endTime is how we know the window has passed)
> fee window advance

- src/blockchain/log-processors/database.ts
- src/blockchain/log-processors/initial-report-submitted.ts
- src/blockchain/log-processors/market-finalized.ts
- src/blockchain/process-block.ts
A little cleaner to act on trx object directly, prevents queries that aren't a part of tx from being queried
> transaction argument change

- config.json
- src/blockchain/sync-augur-node-with-blockchain.ts
- yarn.lock
> gotta go fast

- src/blockchain/sync-augur-node-with-blockchain.ts
might be slightly older than reality, but not important here
honestly, we'll probably want to subtract ~6 blocks from this number anyway
> use the same source that augur.js uses to fetch block numbers.

- src/server/getters/get-market-price-history.ts
- src/types.ts
- test/server/getters/get-market-price-history.js
> 40 story points

- .travis.yml
- package-lock.json
- package.json
- src/blockchain/log-processors/order-canceled.ts
- test/blockchain/log-processors/initial-report-submitted.js
Also added a market ID and outcome lookup to order-canceled log processor and attach it to the emitter.
> Updated designated reporting label

- src/server/getters/get-contract-addresses.ts
- test/server/getters/get-contract-addresses.js
> add net_version to contract addresses

- src/blockchain/process-block.ts
requires new constants in augur.js
> move markets into open_reporting if designated reporter doesn't show up.

- src/blockchain/log-processors/index.ts
- src/blockchain/log-processors/initial-report-redeemed.ts
- src/blockchain/log-processors/initial-report-submitted.ts
- src/blockchain/log-processors/initial-report-transferred.ts
- src/blockchain/log-processors/token/burn.ts
- src/blockchain/log-processors/token/decrease-token-balance.ts
- src/blockchain/log-processors/token/increase-token-balance.ts
- src/blockchain/log-processors/token/mint.ts
- src/blockchain/log-processors/tokens-transferred.ts
- src/migrations/20171015155157_initial_reports.ts
- src/migrations/20171102152617_disputes.ts
- src/seeds/test/balances.ts
- src/seeds/test/initial_reports.ts
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-dispute-tokens.ts
- src/server/getters/get-initial-reporters.ts
- src/types.ts
- test/blockchain/log-processors/crowdsourcers.js
- test/blockchain/log-processors/initial-report-redeemed.js
- test/blockchain/log-processors/initial-report-submitted.js
- test/blockchain/log-processors/initial-report-transferred.js
- test/blockchain/log-processors/tokens-burned.js
- test/blockchain/log-processors/tokens-minted.js
- test/blockchain/log-processors/tokens-transferred.js
- test/server/getters/get-dispute-tokens.js
- test/server/getters/get-initial-reporters.js
This also includes some updates to the getter for dispute tokens as well as support for generic token balance tracking with the balances table.
> Get initial reporters

- src/blockchain/log-processors/token/burn.ts
- src/blockchain/log-processors/token/mint.ts
fix issue with handling different token log types
> fix for handling different event types in same method

- src/blockchain/start-augur-listeners.ts
- src/seeds/test/balances.ts
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-initial-reporters.ts
- src/types.ts
- test/server/getters/get-initial-reporters.js
Some additions to log listeners as well as some tweaks to the initial reporters getter
> Stake token fixes

- src/seeds/test/positions.ts
- src/server/getters/get-user-trading-positions.ts
- test/blockchain/log-processors/completesets.js
- test/blockchain/log-processors/order-filled/index.js
- test/server/getters/get-user-trading-positions.js
> Added share adjustments on-the-way-out in getUserTradingPositions

- src/blockchain/log-processors/database.ts
- src/blockchain/process-block.ts
Reverts AugurProject/augur-node#228
> Revert "advance awaiting fee window"

- src/blockchain/log-processors/crowdsourcer.ts
- src/blockchain/log-processors/initial-report-submitted.ts
- src/blockchain/log-processors/market-finalized.ts
- src/server/getters/database.ts
- src/server/getters/get-dispute-info.ts
- src/server/getters/get-markets-info.ts
- src/types.ts
- test/blockchain/log-processors/market-finalized.js
- test/blockchain/log-processors/universe-created.js
- test/server/getters/get-markets-info.js
types cleaned up now, this should do what you need  @JohnDanz
> store winning payout, retrieve in markets-info

- src/index.ts
Resolves [ch7794] https://app.clubhouse.io/augur/story/7794/add-error-event-object-to-disconnect-events
Note: depends on https://github.com/ethereumjs/ethrpc/pull/55 and https://github.com/AugurProject/augur.js/pull/271
> Added event parameter to Ethereum disconnect callback

- src/blockchain/log-processors/order-created.ts
- src/blockchain/log-processors/order-filled/index.ts
- src/blockchain/log-processors/order-filled/update-orders-and-positions.ts
- src/blockchain/log-processors/order-filled/update-volumetrics.ts
- src/utils/convert-fixed-point-to-decimal.ts
- test/blockchain/log-processors/order-created.js
- test/blockchain/log-processors/order-filled/index.js
Resolves https://app.clubhouse.io/augur/story/7852/scalar-order-creation-transactions-fail
Requires https://github.com/AugurProject/augur.js/pull/280
> Fixed scalar order calculations

- src/server/run-websocket-server.ts
@stephensprinkle I believe this was the cause of your augur-node error
> protect all websocket.send

- src/blockchain/log-processors/universe-created.ts
- src/migrations/20180123152617_universes.ts
- src/seeds/test/payouts.ts
- src/seeds/test/token_supply.ts
- src/seeds/test/universes.ts
- src/server/address-format-reviver.ts
- src/server/getters/get-fork-migration-totals.ts
- src/types.ts
- test/blockchain/log-processors/universe-created.js
- test/server/getters/get-fork-migration-totals.js
handle the new universe logging data and provide a getter to retrieve migration totals
> modify universe creation and provide  universe migration totals getter

- src/server/dispatch-json-rpc-request.ts
> Add getter to registry

- package.json
added 'nuke' to really clean augur-node dir.
> added the nuclear option

- src/server/getters/get-categories.ts
- test/server/getters/get-categories.js
> Hack to convert category popularity value to a string

- src/blockchain/log-processors/index.ts
- src/blockchain/log-processors/market-migrated.ts
- test/blockchain/log-processors/market-migrated.js
process the market migrated event
> process market migrated events

- package-lock.json
- package.json
- src/blockchain/log-processors/order-filled/index.ts
- src/blockchain/log-processors/order-filled/refresh-position-in-market.ts
- src/constants.ts
Also changed to full precision.  Resolves [ch8512](https://app.clubhouse.io/augur/story/8512/orderfilled-log-removal-should-have-the-same-fields-as-the-log-addition)
> 8512 order filled log removal

- src/blockchain/process-block.ts
added eventName and universe to MarketState emitter.
Let me know if there is a better way to put universe on the market state emitter. I think best would be to get it out of the Markets table. I don't know if in the future logs will be coming in from multiple universes. I assume so.
> added eventName and universe to MarketState emiter

- src/blockchain/log-processors/crowdsourcer.ts
- src/server/getters/get-dispute-info.ts
- test/server/getters/get-dispute-info.js
ensure proper ordering of completion setting
> act on crowdsourcer completion state when completing one crowdsourcer

- app.json
Changed repo URL from: `http://github.com/augut/augur-node` to `http://github.com/augurproject/augur-node` in `app.json`.
> Whos augut?

- package.json
- src/index.ts
- src/server/run-server.ts
- src/server/run-websocket-server.ts
- src/types.ts
Also bumped the version so I can publish a new package too
> return http(s) servers along with ws ones to accomodate clean shutdown

- package.json
- src/server/run-websocket-server.ts
small thing to run AN from within the app
> use correct paths when we don't know the execution directory

- src/server/run-websocket-server.ts
This should address https://app.clubhouse.io/augur/story/9296/augur-node-epipe-error
> Handle errors

- src/blockchain/process-block.ts
- src/blockchain/start-augur-listeners.ts
- src/blockchain/sync-augur-node-with-blockchain.ts
Not sure how the fix for the health check setInterval got removed but noticed that needed to be added back too.
> use main error callback when processing new blocks. Also add health fix

- src/server/getters/get-reporting-fees.ts
- test/server/getters/get-reporting-fees.js
The spec is at https://docs.google.com/document/d/1PBa8F2_ZlD3YTve7Dy9PUGM8h_A_qeJKwRfn1PK6Gy4/edit
> Updating getReportingFees to return markets/reporting participants as per updated spec

- src/server/getters/get-fee-window-current.ts
- test/server/getters/get-fee-window-current.js
- yarn.lock
@bthaile would you like to have these values separated in the output? I add them into totalStake in the response object, but i could deliver the participationTokens and other reports separately
> Add participation tokens to x rep staked

- src/server/getters/get-fee-windows.ts
Still need to return PTs when the fee window has no cash balance
> Fix for no cash pts

- src/server/getters/get-reporting-fees.ts
- test/server/getters/get-reporting-fees.js
- Adds PT stake to the unclaimed stake total
- Adds crowdsourcers and initial Reporter to forked market
> add missing data to get-reporting-fees

- test/blockchain/log-processors/market-mailbox-transferred.js
Only noticed because it didn't get db.destroy() treatment and was hanging my local tests
> Test for market-mailbox-transferred, forgot to include with original PR i guess

- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-markets-created-by-user.ts
- test/server/getters/get-markets-created-by-user.js
just a little missing feature we use in the UI
> add earliestCreationTime to getMarketsCreatedByUser

- src/blockchain/process-block.ts
Story details: https://app.clubhouse.io/augur/story/11034
> Incorrect values displayed for designated reporter for get reporting fees.

- scripts/release-docker.sh
fixes a bug in the deploy script so we refresh the cluster properly
> set augur service correctly

- src/blockchain/log-processors/fee-window-created.ts
- src/blockchain/log-processors/market-created.ts
- src/migrations/20171005131812_tokens.ts
- src/server/getters/get-reporting-fees.ts
- test/blockchain/log-processors/fee-window-created.js
- test/blockchain/log-processors/market-created.js
So i ended up cleaning up some stuff and added tokens.feeWindow and whatnot, but then I realized the fix might not require it at all? Still seeing if the sql works out the way i want to it, but i thought it'd be worth a review
> fix augur node getreportingfees to protect against participant getter other token on it

- src/server/getters/get-profit-loss.ts
- test/server/getters/get-profit-loss.js
Story details: https://app.clubhouse.io/augur/story/11438
May add market/outcome filters now
> [WIP] PL looks incorrect on Position

- src/blockchain/log-processors/market-created.ts
- src/server/getters/get-user-share-balances.ts
> Fix issue with too many share balances being returned

- src/server/getters/get-reporting-fees.ts
Was getting the fees correctly but not returning the actual crowdsourcer since the market fee window won't be complete yet.
> crowdsourcer fee window is static

- package-lock.json
- package.json
> Mvp update

- src/blockchain/sync-augur-node-with-blockchain.ts
- src/server/getters/get-contract-addresses.ts
- src/server/run-server.ts
- test/server/getters/get-contract-addresses.js
/status/sync
and
getContractAddresses
> finished sync check

- .travis.yml
add mvp to list of branches that run travis
> travis needs to run on mvp branch

- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-account-transfer-history.ts
- test/unit/server/getters/get-account-transfer-history.js
add looking for transaction hash in orders table as well as trades.
> add looking in orders table for same transactionHash as token transfer

- src/server/getters/get-profit-loss.ts
- test/unit/server/getters/get-profit-loss.js
> Allow getProfitLoss to be called with no start/end time and to do the

- package.json
short term fix for cleaning augur db file.
> clean needs to remove augur db, the file name format has changed

- src/blockchain/download-augur-logs.ts
and add a log processing queue so augur.js can continue fetching and giving us batches.
It is augur-node's responsibility to serialize the batches
> Change bulk sync to accept batches of logs from augur.js

- src/blockchain/log-processors/order-created.ts
- src/migrations/20171005123242_orders.ts
- src/server/getters/get-all-orders.ts
- src/server/getters/get-better-worse-orders.ts
- src/server/getters/get-orders.ts
- test/unit/blockchain/log-processors/order-canceled.js
- test/unit/blockchain/log-processors/order-created.js
- test/unit/blockchain/log-processors/order-filled/index.js
Causes issues with upsert of isRemoved row
Last "isRemoved" left
> Get rid of the "isRemoved" concept from orders

- .gitignore
> Added wildcard to augur db in gitignore

- package-lock.json
- package.json
> 0.2.15 version bump

- package-lock.json
- package.json
bump version of augur.js to version -19
> Bump version 19

- src/controller.ts
- src/setup/check-and-initialize-augur-db.ts
// We'll need to make this work with postgres after merging #294
> Controller can rename DB

- src/blockchain/bulk-sync-augur-node-with-blockchain.ts
- src/controller.ts
, makes more sense anyway and we have access to database dir
> Change where we call saveBulkSync

- package.json
This is why -11 didn't have the code you expected
> Build when versioning

- src/setup/check-and-initialize-augur-db.ts
Will only work with updated augur.js that includes updated augur-core
>  add ipc endpoint

- src/controller.ts
- src/setup/check-and-initialize-augur-db.ts
Story details: https://app.clubhouse.io/augur/story/4093
> PostgreSQL Compatibility

- src/setup/check-and-initialize-augur-db.ts
> Add back rename

- package.json
This shouldn't be done like this!
> Remove the git init

- package-lock.json
- package.json
- yarn.lock
> Augur.js@5.5.0

- src/index.ts
This reverts commit 011f2dcd01442e5b9c28c7cdb207cce050e520cc.
> Revert "Add index file to simplify use as a library"

- src/index.ts
This reverts commit d35d157b7a55712a994f42cc6484f02251461490.
> Revert "Revert "Add index file to simplify use as a library""

- package.json
- src/migrations/20180907121300_outcome_market_share_volume.ts
I ran this manually against a populated Rinkeby DB and it worked without error now.
> fix query and some casting issues

- src/controller.ts
Story details: https://app.clubhouse.io/augur/story/13939
> Make use of ethrpc disconnect function in Augur Node

- src/blockchain/log-processors/database.ts
- src/blockchain/log-processors/initial-report-submitted.ts
- src/blockchain/log-processors/market-created.ts
- src/blockchain/log-processors/universe-created.ts
Fix updateMarketFeewindow to only hit chain if necessary
> Re-order off-chain calls to top of processing

- src/blockchain/download-augur-logs.ts
- src/blockchain/make-log-listener.ts
- src/blockchain/process-block.ts
- src/blockchain/process-queue.ts
Please try this before merging.
> Fix the hanging of db writes on blockstream

- package-lock.json
- src/blockchain/download-augur-logs.ts
- src/blockchain/make-log-listener.ts
- src/blockchain/process-block.ts
- src/migrations/20171005123302_blocks.ts
- src/migrations/20181109151249_transactionHashes.ts
- src/migrations/20181110071746_add_bulk_sync.ts
- src/types.ts
adding some information useful when debugging
> add bulksSync column and record tx hashes

- src/server/getters/get-proceed-trade-rows.ts
- test/unit/server/getters/get-profit-loss.js
Fixed formatting amount of claimed proceeds so that P/L calculations are correct and user positions show amount of 0.
> found the amount formatting issue, no more neg positions after claiming

- src/blockchain/log-processors/order-canceled.ts
- src/blockchain/log-processors/order-created.ts
- src/blockchain/log-processors/order-filled/index.ts
- src/blockchain/log-processors/profit-loss/update-outcome-value.ts
> Use the last order filled price

- jest.config.js
- test/setup.js
(See https://github.com/AugurProject/augur/pull/867/files)
> Bump jest timeout to 15s

- src/blockchain/bulk-sync-augur-node-with-blockchain.ts
Fixes AugurProject/augur#260
Code is ready.
**But**, the Alchemy doesn't implement `eth_syncing`; they return status 400 "unsupported method", and ethrpc intercepts this 400 and emits a disconnected event which causes "Disconnected from Ethereum node", breaking everything.
The simplest fix here is to request that Alchemy implement eth_syncing, even if they just always return `false`. I'll request this of them and report back here.
> Don't start augur-node sync until the Ethereum node done syncing

- test/unit/blockchain/log-processors/order-filled/index.js
> Don't test for openInterest when testing processOrderFilledLog()

- src/blockchain/log-processors/order-filled/index.ts
- src/blockchain/log-processors/order-filled/update-order.ts
- src/blockchain/log-processors/profit-loss/update-profit-loss.ts
- src/constants.ts
- src/migrations/20181009111121_profit_loss_timeseries.ts
- src/server/getters/get-profit-loss.ts
- src/server/getters/get-user-trading-positions.ts
- test/unit/server/getters/get-profit-loss.js
- test/unit/server/getters/get-user-trading-positions.js
Fixes https://github.com/AugurProject/augur/issues/825
> Fix net and avg price

- src/blockchain/log-processors/profit-loss/update-profit-loss.ts
- src/migrations/20190201155650_wcl_profit_loss_timeseries.ts
Another pull request from me fixing migrations to be compatible with Postgres 🙂
> Fix migration to be compatible with Postgres

- package-lock.json
- src/server/dispatch-json-rpc-request.ts
- src/server/getters/get-account-time-ranged-stats.ts
- test/unit/server/getters/get-account-time-ranged-stats.js
Supplies
- Positions
- markets created
- number of trades
- successful disputes
- markets traded
- redeemed positions
> augur-1277 account time ranged stats

- src/server/getters/get-platform-activity-stats.ts
- test/unit/server/getters/get-platform-activity-stats.ts
Volume was being incorrectly calculated off of markets but it should be calculated off of trades.
This PR fixes the sql query.
> Change volume in platform stats to trades.volume

- src/server/getters/get-account-transaction-history.ts
Fixes https://github.com/AugurProject/augur/issues/1656
> Fix off-by-10 bug

- src/server/getters/get-account-transaction-history.ts
- src/types.ts
- src/utils/dimension-quantity.ts
- src/utils/financial-math.ts
Add new types to finmath lib: TradeCost, TradeCostIncludingFees,
TradeBuyOrSell, TradeQuantity, ReporterFees, MarketCreatorFees, TotalFees.
> Use finmath library to calculate trade cost in getAccountTransactionHistory

- src/server/getters/get-markets.ts
- test/unit/server/getters/get-markets.js
> Add maxEndTime filter to getMarkets

- src/controller.ts
removing eth gas station call, issues making the call when deploying in AWS
> remove eth gas stations call for diagnosis

- src/migrations/20190524103839_add_outcomes_liquidity_and_markets_liquidity.ts
Reverts AugurProject/augur-node#913
> Revert "Update markets_liquidity CREATE VIEW for Postgres"

- src/migrations/20190524103839_add_outcomes_liquidity_and_markets_liquidity.ts
Added quotes and a subquery alias
> Update markets_liquidity CREATE VIEW for Postgres
